openapi: 3.0.0
info:
  title: Epic Movie Quotes
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /movies:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies"
  /movies/{id}:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies~1{id}"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Movies:
      allOf:
        - $ref: "./_swagger/schemas/movies.yaml#/components/schemas/Movies"
    